name: Solidity CI

on:
  workflow_dispatch:
    inputs:
      runner_type:
        description: "Runner type: 'self-hosted' (default) or 'github-hosted'"
        required: false
        type: choice
        default: self-hosted
        options:
          - self-hosted
          - github-hosted
  push:

jobs:
  build:

    runs-on: ${{ fromJson((github.event.inputs.runner_type || 'self-hosted') == 'self-hosted' && '["self-hosted","ARM64"]' || '["arm-runner"]') }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Compile contracts and check TypeScript
      run: npm run build

    - name: Check code is formatted
      run: npm run format-check

    - name: Lint code
      run: npm run lint

    - name: Check docs are up to date
      run: |
        npm run docs
        git diff --exit-code docs/ || (echo "Documentation is outdated. Please update it by running 'npm run docs' and committing the changes." && exit 1)
