name: Publish Package to npmjs
on:
  workflow_dispatch:
    inputs:
      runner_type:
        description: "Runner type: 'self-hosted' (default) or 'github-hosted'"
        required: false
        type: choice
        default: self-hosted
        options:
          - self-hosted
          - github-hosted
  release:
    types: [published]
jobs:
  build:
    runs-on: ${{ fromJson(github.event_name == 'release' && '["ubuntu-latest"]' || ((github.event.inputs.runner_type || 'self-hosted') == 'self-hosted' && '["self-hosted","ARM64"]' || '["arm-runner"]')) }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
